from __future__ import division

# Copyright (c) 2015-2022 The Switch Authors. All rights reserved.
# Licensed under the Apache License, Version 2, which is in the LICENSE file.

import os
from pyomo.environ import *


from switch_model.utilities import unique_list

"""

This module defines a regional Renewable Portfolio Standard (RPS) policy scheme
for the Switch model. In this scheme, each generator in each zone is categorized as RPS-
elegible or not.
Dispatched electricity that is generated by RPS-elegible sources in each
period and zone is summed up and must meet an energy goal in each zone, set as a required percentage
of all energy that is generated in that period.

This module assumes that the generators.core.no_commit module is being used.
An error will be raised if this module is loaded along the
generators.core.commit package.
"""


def define_components(m):
    """
    ESR_PROGRAM is a set of program/regions that have target shares of "clean energy".
    ESR_GEN is a set of generators that are eligible for producing "clean energy"(RPS-eligible).

    load_zone is a subset of model regions where RPS goals are defined.
    rps_share[z in load_zone] is the fraction of total generated energy in
        a period in a zone that has to be provided by RPS-elegible generators.
    """
    # indexing set for the zonal requirements: (program, period, zone) combination
    # (These are all the index columns from esr_requirement.csv.)
    m.ESR_RULES = Set(dimen=3, within=Any * m.PERIODS * m.LOAD_ZONES)

    # share target specified for each (program, period, zone) combination
    m.rps_share = Param(m.ESR_RULES, default=float("inf"), within=Reals)

    # names of all the ESR programs and periods when they are in effect;
    # each unique pair of values in the first two columns of
    # ESR_requirement.csv is a (program, period) combo
    m.ESR_PROGRAM_PERIODS = Set(
        dimen=2,
        within=Any * m.PERIODS,
        initialize=lambda m: unique_list((pr, pe) for pr, pe, z in m.ESR_RULES),
    )

    # set of ESR programs
    m.ESR_PROGRAMS = Set(
        initialize=lambda m: unique_list(pr for pr, pe in m.ESR_PROGRAM_PERIODS)
    )

    # set of zones that participate in a particular ESR program in a particular period
    m.ZONES_IN_ESR_PROGRAM_PERIOD = Set(
        m.ESR_PROGRAM_PERIODS,
        within=m.LOAD_ZONES,
        initialize=lambda m, pr, pe: [
            _z for (_pr, _pe, _z) in m.ESR_RULES if (_pr, _pe) == (pr, pe)
        ],
    )

    # set of all valid program/generator combinations (i.e., gens participating
    # in each program)
    m.ESR_PROGRAM_GENS = Set(within=m.ESR_PROGRAMS * m.GENERATION_PROJECTS)
    m.GENS_IN_ESR_PROGRAM = Set(
        m.ESR_PROGRAMS,
        within=m.GENERATION_PROJECTS,
        initialize=lambda m, pr: unique_list(
            _g for (_pr, _g) in m.ESR_PROGRAM_GENS if _pr == pr
        ),
    )

    # enforce constraint on regional rps energy share in each program for zones in each period
    def rule(m, pr, pe):
        # zonal demand for this program/period
        zonal_demand_share = sum(
            m.rps_share[pr, pe, z] * m.zone_total_demand_in_period_mwh[z, pe]
            for z in m.ZONES_IN_ESR_PROGRAM_PERIOD[pr, pe]
        )

        # sum of annual dispatched energy for gens in this program in this period
        EligibleEnergy = sum(
            m.DispatchGen[g, t] * m.tp_weight[t]
            for g in m.GENS_IN_ESR_PROGRAM[pr]
            if g in m.GENS_IN_PERIOD[pe]
            for t in m.TPS_FOR_GEN_IN_PERIOD[g, pe]
        )

        # define and return the constraint
        return EligibleEnergy >= zonal_demand_share

    m.Enforce_RPS_Share = Constraint(m.ESR_PROGRAM_PERIODS, rule=rule)


def load_inputs(mod, switch_data, inputs_dir):
    """
    The RPS target goals input file is mandatory, to discourage people from
    loading the module if it is not going to be used. It is not necessary to
    specify targets for all periods.

    Mandatory input files:
        esr_generators.csv
            ESR_PROGRAM, ESR_GEN

        esr_requirement.csv:
           ESR_PROGRAM, PERIOD, load_zone, rps_share

    """

    switch_data.load_aug(
        filename=os.path.join(inputs_dir, "esr_generators.csv"),
        optional=True,  # also enables empty files
        set=mod.ESR_PROGRAM_GENS,
    )

    switch_data.load_aug(
        filename=os.path.join(inputs_dir, "esr_requirements.csv"),
        optional=True,  # also enables empty files
        index=mod.ESR_RULES,
        param=(mod.rps_share,),
    )
